name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: |
        IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/drugwarehouse-api:latest
        docker build . --file Dockerfile --tag $IMAGE_TAG

    - name: Push the Docker image
      run: |
        IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/drugwarehouse-api:latest
        docker push $IMAGE_TAG
    - name: SSH and run build on remote server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem root@103.90.227.104 << 'EOF'
            cd DrugWarehouseManagement_BE/
            ./dc pull api && ./dc up api -d
          EOF
        shell: bash
