name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.cs"
      - "**/*.csproj"
      - "**/*.sln"
      - "Dockerfile"
      - ".dockerignore"
      - ".github/workflows/docker-image.yml"
      - "docker-compose*.yml"
  workflow_dispatch:  # Allow manual triggering

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone for faster checkout

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64
          driver-opts: |
            network=host

      # Only set up QEMU if you actually need multi-architecture builds
      # Removed QEMU setup since we're only targeting linux/amd64

      - name: Docker layer caching
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/drugwarehouse-api
          tags: |
            type=sha,format=short
            type=raw,value=latest,enable={{is_default_branch}}
          flavor: |
            latest=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            BUILD_CONFIGURATION=Release
          platforms: linux/amd64
          outputs: type=registry

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Deploy to remote server
        if: success()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 103.90.227.104
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd DrugWarehouseManagement_BE/
            ./dc -f docker-compose.production.yml pull api && ./dc -f docker-compose.production.yml up api -d