name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Recreate Firebase credentials file
      run: |
        echo "${{ secrets.FIREBASE_CREDENTIALS }}" > firebase-service-account.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/firebase-service-account.json" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: |
        IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/drugwarehouse-api:latest
        docker build . --file Dockerfile --tag $IMAGE_TAG

    - name: Push the Docker image
      run: |
        IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/drugwarehouse-api:latest
        docker push $IMAGE_TAG

    - name: Clean up credentials
      run: rm firebase-service-account.json
