name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.cs"
      - "**/*.csproj"
      - "**/*.sln"
      - "Dockerfile"
      - ".dockerignore"
      - ".github/workflows/docker-image.yml"
      - "docker-compose*.yml"
  workflow_dispatch:  # Allow manual triggering

env:
  DOCKER_BUILDKIT: 1  # Enable BuildKit
  BUILDKIT_PROGRESS: plain
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone for faster checkout

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64  # Specify platform for deterministic builds
          driver-opts: |
            image=moby/buildkit:v0.12.0
            network=host
          config-inline: |
            [worker.oci]
              max-parallelism = 4
              gc = true
              gckeepstorage = 20000
            
            [worker.containerd]
              max-parallelism = 4
              gc = true
              gckeepstorage = 20000

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker layer caching
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile', '**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/drugwarehouse-api
          tags: |
            type=sha,prefix=
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
          flavor: |
            latest=true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            BUILD_CONFIGURATION=Release
          platforms: linux/amd64
          # Added options for debugging build issues
          progress: plain
          # Removed potentially problematic optimizations
          outputs: type=registry
          allow: network.host

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Deploy to remote server
        if: success()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 103.90.227.104
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd DrugWarehouseManagement_BE/
            ./dc -f docker-compose.production.yml pull api && ./dc -f docker-compose.production.yml up api -d