name: .NET Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the solution
      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      # Step 5: Run tests
      - name: Run Tests
        run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=test_results.trx" --results-directory ./test-results

      # Step 6: Debug Test Results File
      - name: Debug test results
        if: always() # Ensures this step runs even if previous steps fail
        run: |
          if [ -f "./test-results/test_results.trx" ]; then
            echo "Test Results File Found:"
            cat ./test-results/test_results.trx
          else
            echo "Test Results File Not Found"
          fi

      - name: Parse Passed Tests Count
        id: parse_tests
        run: |
          passed_tests=$(xmllint --xpath "string(//TestRun/Result[@outcome='Passed']/@outcome)" ./test-results/test_results.trx | wc -l)
          echo "Passed tests count: $passed_tests"
          echo "passed_tests=$passed_tests" >> $GITHUB_ENV

      - name: Show Passed Tests in Workflow Output
        run: echo "Number of passed tests: ${{ env.passed_tests }}"

      # Step 8: Publish test results
      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: ./test-results
