name: .NET Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the solution
      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      # Step 5: Run tests
      - name: Run unit tests
        run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=test_results.trx" --results-directory ./test-results

      # Step 6: Publish test results
      - name: Publish test results
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ./test-results

      # Step 7: Check passed test cases
      - name: Check passed test cases
        run: |
          passed=$(grep -oP '(?<=Passed: )\d+' ./test-results/test_results.trx | paste -sd+ | bc)
          echo "Total Passed Test Cases: $passed"
          echo "::set-output name=passed::$passed"
        shell: bash